import { Grid } from '@mantine/core';
import { getPerformance } from "firebase/performance";
import Head from 'next/head';
import React from "react";
import useSWR from 'swr';
import MovieCard from "../components/MovieCard/MovieCard";
import SearchMovie from "../components/SearchMovie/SearchMovie";
import firebaseApp from '../lib/firebase';
import { useAuth } from "../lib/firebase.auth";
import styles from '../styles/Home.module.css';

if (typeof window !== 'undefined') {
  getPerformance(firebaseApp);
}

const fetcher = async (url) => {
  const res = await fetch(url);
  if (!res.ok) throw new Error('Failed to fetch');
  return res.json();
};

export default function Home() {
  const { user } = useAuth();
  const { data: posts, error } = useSWR(
    `https://api.themoviedb.org/3/discover/movie?api_key=${process.env.NEXT_PUBLIC_MOVIEDB_API_KEY}`,
    fetcher
  );

  if (error) return <div>Failed to load movies</div>;
  if (!posts) return <div>Loading...</div>;

  return (
    <div className={styles.container}>
      <Head>
        <title>Five Stars</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Discover
        </h1>

        <SearchMovie/>

        <Grid gutter="lg">
          {posts.results?.map(movie => (
            <Grid.Col span={{ base: 6, lg: 4 }} key={movie.id}>
              <MovieCard movie={movie} user={user}/>
            </Grid.Col>
          ))}
        </Grid>
      </main>
    </div>
  )
}
